"""
Project Euler
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


author:  Adam Shechter
"""


def main():
    penta_series_list = pentagonal_series(10000)
    print(penta_series_list)
    print(find_symm_pents(penta_series_list))


def pentagonal_series(upper_limit):
    pent_list = []
    for i in range(1, upper_limit):
        pent_val = i * (3 * i - 1) // 2
        pent_list.append(pent_val)
    return pent_list


def find_symm_pents(penta_series_list):
    for i1 in range(len(penta_series_list)):
        for i2 in range(i1+1, len(penta_series_list)):
            n1 = penta_series_list[i1]
            n2 = penta_series_list[i2]
            if (n1 + n2) in penta_series_list:
                print("Sum Pentagonal: {} + {} = {}".format(n1, n2, n1+n2))
                if abs(n2 - n1) in penta_series_list:
                    print("*"*50)
                    print("Difference Pentagonal: {} - {} = {}".format(n1, n2, abs(n2 - n1)))
                    return n1, n2
    return False

if __name__ == '__main__':
    main()
